In [22]:
!pip install fuzzywuzzy
import pandas as pd
from fuzzywuzzy import fuzz

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

Results:

Gemma2b:

untrained_Gemma2b_commonsense_responses: 54/200 == 27%

untrained_Gemma2b_gsm8k_responses: 35/100 = 35%

untrained_Gemma2B_Multi_responses: 28/108 = 25.9%

untrained_Gemma2b_Wiki_responses: 17/100 = 17%



Mistral7b:

untrained_Mistral7b_commonsense_responses: 45/200 = 22.5%

untrained_Mistral7b_gsm8k_responses: 26/100 = 26%

untrained_Mystral7B_Multi_responses: 29/108 = 26.8%

untrained_Mystral7B_Wiki_responses: 17/100 = 17%

In [29]:
df = pd.read_pickle("/content/drive/MyDrive/NLP_project/Abhishek (Mutli tool Chained- hotpot)/Baseline_result/untrained_Gemma2b_Wiki_responses.pkl")

In [30]:
df

,id,Q,A,type,level,supporting_facts,W,untrained_Gemma2b_ans,Bool
0,5a879ab05542996e4f30887e,The Oberoi family is part of a hotel company t...,Delhi,bridge,medium,"{'title': ['Oberoi family', 'The Oberoi Group'...","{'title': ['Ritz-Carlton Jakarta', 'Oberoi fam...",\n\nA. New York\nB. Los Angeles\nC. London\nD....,False
1,5a8d7341554299441c6b9fe5,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,bridge,hard,"{'title': ['Allie Goertz', 'Allie Goertz', 'Al...","{'title': ['Lisa Simpson', 'Marge Simpson', 'B...","\n\nThe correct answer is ""The Simpsons"" creat...",False
2,5a82171f5542990a1d231f4a,What nationality was James Henry Miller's wife?,American,bridge,medium,"{'title': ['Peggy Seeger', 'Peggy Seeger', 'Ew...","{'title': ['Moloch: or, This Gentile World', '...",\n\nA. English\n\nB. French\n\nC. Irish\n\n...,False
3,5a84dd955542997b5ce3ff79,Cadmium Chloride is slightly soluble in this c...,alcohol,bridge,medium,"{'title': ['Cadmium chloride', 'Ethanol'], 'se...","{'title': ['Cadmium chloride', 'Water blue', '...",\n\nAnswer:\n\nStep 1/2\nCadmium Chloride is a...,False
4,5adf44985542993a75d2646d,Which genus of moth in the world's seventh-lar...,Crambidae,bridge,hard,"{'title': ['Indogrammodes', 'Indogrammodes', '...","{'title': ['India', 'List of companies of Indi...",\n\nWhich of the following is NOT a characteri...,False
...,...,...,...,...,...,...,...,...,...
95,5ae3345f55429928c4239682,Are both Tim McIlrath and Spike Slawson Americ...,yes,comparison,medium,"{'title': ['Tim McIlrath', 'Spike Slawson'], '...","{'title': ['Give It All', 'Tim McIlrath', 'The...",\n\nTim McIlrath is from the U.S. and Spike Sl...,False
96,5abf037a5542993fe9a41dbe,What profession does Am Rong and Alexandre Roc...,filmmaker,comparison,medium,"{'title': ['Am Rong', 'Alexandre Rockwell'], '...","{'title': ['Somebody to Love (film)', 'Four Ro...",\n\nAnswer:\n\nStep 1/2\nAm Rong and Alexandre...,False
97,5ab3ed12554299753aec59f3,El Nuevo Cojo and Golf Magazine are both speci...,Golf Magazine,comparison,medium,"{'title': ['El Nuevo Cojo', 'El Nuevo Cojo', '...",{'title': ['Australian Law Librarians' Associa...,\n\nThe answer is that El Nuevo Cojo is owned ...,False
98,5a74f2ff5542993748c89748,What city are George Washington University Hos...,"Washington, D.C.",comparison,medium,{'title': ['George Washington University Hospi...,{'title': ['Southend University Hospital NHS F...,\n\nWhat is the capital of New York state?\n\n...,False
99,5ab9672655429970cfb8eabd,Which industry do Richard Hawley and Chicago's...,rock band,comparison,easy,{'title': ['Catherine (alternative rock band)'...,"{'title': ['Late Night Final', 'Lady's Bridge ...",\n\n<em>The Chicago Tribune</em> recently aske...,False

In [31]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
len(df[df["Bool"] == True])

0

In [33]:

print(df["untrained_Gemma2b_ans"][3])

Answer:

Step 1/2
Cadmium Chloride is a chemical compound with the formula CdCl2. It is also known as cadmi...

Step 2/2
Read More

In [34]:
df

,id,Q,A,type,level,supporting_facts,W,untrained_Gemma2b_ans,Bool
0,5a879ab05542996e4f30887e,The Oberoi family is part of a hotel company t...,Delhi,bridge,medium,"{'title': ['Oberoi family', 'The Oberoi Group'...","{'title': ['Ritz-Carlton Jakarta', 'Oberoi fam...",\n\nA. New York\nB. Los Angeles\nC. London\nD....,False
1,5a8d7341554299441c6b9fe5,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,bridge,hard,"{'title': ['Allie Goertz', 'Allie Goertz', 'Al...","{'title': ['Lisa Simpson', 'Marge Simpson', 'B...","\n\nThe correct answer is ""The Simpsons"" creat...",False
2,5a82171f5542990a1d231f4a,What nationality was James Henry Miller's wife?,American,bridge,medium,"{'title': ['Peggy Seeger', 'Peggy Seeger', 'Ew...","{'title': ['Moloch: or, This Gentile World', '...",\n\nA. English\n\nB. French\n\nC. Irish\n\n...,False
3,5a84dd955542997b5ce3ff79,Cadmium Chloride is slightly soluble in this c...,alcohol,bridge,medium,"{'title': ['Cadmium chloride', 'Ethanol'], 'se...","{'title': ['Cadmium chloride', 'Water blue', '...",\n\nAnswer:\n\nStep 1/2\nCadmium Chloride is a...,False
4,5adf44985542993a75d2646d,Which genus of moth in the world's seventh-lar...,Crambidae,bridge,hard,"{'title': ['Indogrammodes', 'Indogrammodes', '...","{'title': ['India', 'List of companies of Indi...",\n\nWhich of the following is NOT a characteri...,False
...,...,...,...,...,...,...,...,...,...
95,5ae3345f55429928c4239682,Are both Tim McIlrath and Spike Slawson Americ...,yes,comparison,medium,"{'title': ['Tim McIlrath', 'Spike Slawson'], '...","{'title': ['Give It All', 'Tim McIlrath', 'The...",\n\nTim McIlrath is from the U.S. and Spike Sl...,False
96,5abf037a5542993fe9a41dbe,What profession does Am Rong and Alexandre Roc...,filmmaker,comparison,medium,"{'title': ['Am Rong', 'Alexandre Rockwell'], '...","{'title': ['Somebody to Love (film)', 'Four Ro...",\n\nAnswer:\n\nStep 1/2\nAm Rong and Alexandre...,False
97,5ab3ed12554299753aec59f3,El Nuevo Cojo and Golf Magazine are both speci...,Golf Magazine,comparison,medium,"{'title': ['El Nuevo Cojo', 'El Nuevo Cojo', '...",{'title': ['Australian Law Librarians' Associa...,\n\nThe answer is that El Nuevo Cojo is owned ...,False
98,5a74f2ff5542993748c89748,What city are George Washington University Hos...,"Washington, D.C.",comparison,medium,{'title': ['George Washington University Hospi...,{'title': ['Southend University Hospital NHS F...,\n\nWhat is the capital of New York state?\n\n...,False
99,5ab9672655429970cfb8eabd,Which industry do Richard Hawley and Chicago's...,rock band,comparison,easy,{'title': ['Catherine (alternative rock band)'...,"{'title': ['Late Night Final', 'Lady's Bridge ...",\n\n<em>The Chicago Tribune</em> recently aske...,False

In [38]:
import pandas as pd
from fuzzywuzzy import fuzz

def exact_match(text1, text2):
    return text1 == text2

def fuzzy_match(text1, text2):
    ratio = fuzz.partial_ratio(text1.lower(), text2.lower())
    return ratio

def check_answer(row):
    gen = str(row['untrained_Gemma2b_ans'])
    act = str(row['A'])
    if exact_match(gen, act):
        return True
    if gen.find(act) != -1:
        return True
    if gen == act:
        return True
    if fuzzy_match(gen, act) > 70:  # You can adjust the threshold for fuzzy matching
        return True
    return False

# Assuming df is your DataFrame
def apply_comparison(df):
    df['Comparison'] = df.apply(check_answer, axis=1)
    return df

# Example of usage with a DataFrame named df
# df = pd.DataFrame({
#     'untrained_Mystral7b_ans': ['example answer', 'another answer'],
#     'A': ['example answer', 'different answer']
# })

# df = apply_comparison(df)
# print(df)

df = apply_comparison(df)
df

,id,Q,A,type,level,supporting_facts,W,untrained_Gemma2b_ans,Bool,Comparison
0,5a879ab05542996e4f30887e,The Oberoi family is part of a hotel company t...,Delhi,bridge,medium,"{'title': ['Oberoi family', 'The Oberoi Group'...","{'title': ['Ritz-Carlton Jakarta', 'Oberoi fam...",\n\nA. New York\nB. Los Angeles\nC. London\nD....,False,False
1,5a8d7341554299441c6b9fe5,Musician and satirist Allie Goertz wrote a son...,President Richard Nixon,bridge,hard,"{'title': ['Allie Goertz', 'Allie Goertz', 'Al...","{'title': ['Lisa Simpson', 'Marge Simpson', 'B...","\n\nThe correct answer is ""The Simpsons"" creat...",False,False
2,5a82171f5542990a1d231f4a,What nationality was James Henry Miller's wife?,American,bridge,medium,"{'title': ['Peggy Seeger', 'Peggy Seeger', 'Ew...","{'title': ['Moloch: or, This Gentile World', '...",\n\nA. English\n\nB. French\n\nC. Irish\n\n...,False,False
3,5a84dd955542997b5ce3ff79,Cadmium Chloride is slightly soluble in this c...,alcohol,bridge,medium,"{'title': ['Cadmium chloride', 'Ethanol'], 'se...","{'title': ['Cadmium chloride', 'Water blue', '...",\n\nAnswer:\n\nStep 1/2\nCadmium Chloride is a...,False,False
4,5adf44985542993a75d2646d,Which genus of moth in the world's seventh-lar...,Crambidae,bridge,hard,"{'title': ['Indogrammodes', 'Indogrammodes', '...","{'title': ['India', 'List of companies of Indi...",\n\nWhich of the following is NOT a characteri...,False,False
...,...,...,...,...,...,...,...,...,...,...
95,5ae3345f55429928c4239682,Are both Tim McIlrath and Spike Slawson Americ...,yes,comparison,medium,"{'title': ['Tim McIlrath', 'Spike Slawson'], '...","{'title': ['Give It All', 'Tim McIlrath', 'The...",\n\nTim McIlrath is from the U.S. and Spike Sl...,False,False
96,5abf037a5542993fe9a41dbe,What profession does Am Rong and Alexandre Roc...,filmmaker,comparison,medium,"{'title': ['Am Rong', 'Alexandre Rockwell'], '...","{'title': ['Somebody to Love (film)', 'Four Ro...",\n\nAnswer:\n\nStep 1/2\nAm Rong and Alexandre...,False,False
97,5ab3ed12554299753aec59f3,El Nuevo Cojo and Golf Magazine are both speci...,Golf Magazine,comparison,medium,"{'title': ['El Nuevo Cojo', 'El Nuevo Cojo', '...",{'title': ['Australian Law Librarians' Associa...,\n\nThe answer is that El Nuevo Cojo is owned ...,False,True
98,5a74f2ff5542993748c89748,What city are George Washington University Hos...,"Washington, D.C.",comparison,medium,{'title': ['George Washington University Hospi...,{'title': ['Southend University Hospital NHS F...,\n\nWhat is the capital of New York state?\n\n...,False,True
99,5ab9672655429970cfb8eabd,Which industry do Richard Hawley and Chicago's...,rock band,comparison,easy,{'title': ['Catherine (alternative rock band)'...,"{'title': ['Late Night Final', 'Lady's Bridge ...",\n\n<em>The Chicago Tribune</em> recently aske...,False,False

In [39]:
df['Comparison'].unique()

array([False,  True])

In [40]:
len(df[df['Comparison'] == True])

18